### ISSUE TITLE
named parameters isn't defined. please help

### ISSUE THREAD

**Issue by DavyDevelops** [hello-paulvin/city-cab#21]
lib/services/map_services.dart

The named parameter 'desiredAccuracy' isn't defined.at  [107:15]

The named parameter 'timeLimit' isn't defined.at  [108:15]

**Comment by nkosingaleka** [comment]
Fix:

const settings = LocationSettings(
        accuracy: LocationAccuracy.best,
        distanceFilter: 0,
      );

      positionStream = Geolocator.getPositionStream(locationSettings: settings)
          .listen((position) async {
        eventFiring(currentPosition.value);

**Comment by DavyDevelops** [comment]
> Fix:
> 
> const settings = LocationSettings( accuracy: LocationAccuracy.best, distanceFilter: 0, );
> 
> ```
>   positionStream = Geolocator.getPositionStream(locationSettings: settings)
>       .listen((position) async {
>     eventFiring(currentPosition.value);
> ```

Fixed the problem thanks a lot.
