### ISSUE TITLE
_TypeError (type 'Null' is not a subtype of type 'double')

### ISSUE THREAD

**Issue by dwinuroktaviani27** [hello-paulvin/city-cab#22]
_TypeError (type 'Null' is not a subtype of type 'double')

user.dart

latlng: data['latlng'] == null
          ? LatLng(0, 0)
          : LatLng(data['latlng']['lat'], data['latlng']['lng']),

**Comment by edemekong** [comment]
This project is no longer maintained(Contained old codes needs updating), thats why you might not get more fixes for this. However, the value contains null where it should be double that's why its throwing this error.
